### ISSUE TITLE
Reddit minimal

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [zenstorage/Minimal-Reddit#1]
1. is it possible to backup your script separately? i have customized and want to share on the net but can't find the customization.
2. rounding does not work everywhere i set it to 15 
![sshot-007](https://github.com/zenstorage/Minimal-Reddit/assets/73518754/fd27f452-bae5-4ebf-86ff-f3445cb571c9)

**Comment by zenstorage** [comment]
fixed rounded corner in commit 5361ad5
of sure, backup script separately is possivel, what do you want to find

**Comment by subsubsubsubsubsub** [comment]
1. there will be a version for Tampermonkey? 
2.  Will the full picture show without clicking the full picture? 
![sshot-005](https://github.com/zenstorage/Minimal-Reddit/assets/73518754/4c5aa0ae-6894-4a51-a33a-5e12a1ca651b)

**Comment by zenstorage** [comment]
I don't plan on creating a version for tampermonkey, but creating a script to show the entire image might be a good idea, even though the userstyle has an option to show 100% of the image inside the div

**Comment by zenstorage** [comment]
I don't plan on creating a version for tampermonkey, but creating a script to show the entire image might be a good idea, even though the userstyle has an option to show 100% of the image inside the div

**Comment by subsubsubsubsubsub** [comment]
https://chrome.google.com/webstore/detail/new-reddit-enhancements-c/bjnmegcnfngcoknlecbbmkpfkhbaiglh — Here's the code. fix image и добавь. and add. very useful function

**Comment by zenstorage** [comment]
already an option to resize the image in the post:
![image](https://github.com/zenstorage/Minimal-Reddit/assets/82182314/ebdb220f-9674-4df7-a0db-63244dee74d9)
and remove text view full image:
![image](https://github.com/zenstorage/Minimal-Reddit/assets/82182314/75a53cd7-e80d-46ff-8526-0a13ee7fe6a7)

**Comment by subsubsubsubsubsub** [comment]
best
