### ISSUE TITLE
Minimal-Reddit is not working 

### ISSUE THREAD

**Issue by Nangt3c** [zenstorage/Minimal-Reddit#2]
![imagen](https://github.com/zenstorage/Minimal-Reddit/assets/99434490/d53ee905-b576-486b-abb3-2a0c129ba1e0)

**Comment by zenstorage** [comment]
The Minimal Reddit only works on new.reddit.com

**Comment by SEALCOOL13** [comment]
After the update that completely removed new.reddit.com, you have updated the style on 7th September. How can we apply this style now? Trying to apply it on reddit.com/ URLs does not seem to work. Any guidance would be highly appreciated.

**Comment by zenstorage** [comment]
Can you send a screenshot of the version you are on? I tried to reproduce the problem but I can't, I tried to remove and install via https://userstyles.world/style/9384/minimal-reddit but it's working and being applied to new.reddit.com

**Comment by zenstorage** [comment]
@SEALCOOL13 You can try the previous version, the only thing I changed was ident the options: https://github.com/zenstorage/Minimal-Reddit/raw/18595ad00e478eb34fea7dd0a3909a185cf95067/minimal_reddit.user.styl

**Comment by SEALCOOL13** [comment]
![Screenshot from 2024-09-10 07-04-21](https://github.com/user-attachments/assets/04d79c01-556f-4479-b3e2-ed6179ae0266)
![Screenshot from 2024-09-10 07-06-07](https://github.com/user-attachments/assets/b58c5d9f-7497-4c0d-b753-3bd74ef7bcb9)


It does not work with either the normal updated version or the version you linked above, I even disabled my adblocker etc. to see if that was causing an interference. Do I need to somehow activate something from the style settings?

**Comment by zenstorage** [comment]
I misunderstood. You are using the sh layout and said that new.reddit.com has been completely removed. Unfortunately, userstyle doesn't work with this layout (I will practically have to recreate the userstyle to add/make the options work). Maybe it's some A/B testing. I can still access new.reddit.com with the layout.

Unfortunately, until I make it work in sh, the userstyle won't do anything

![image](https://github.com/user-attachments/assets/862e57ed-d96a-4eac-8ec6-4ea772f71611)

I forgot to mention that many elements are inaccessible in this new layout, they isolate elements using shadowRoot so for all options only userstyle will not work

**Comment by SEALCOOL13** [comment]
Thanks for the clarification, hope you can implement it for the new UI, I really wanted to try it as it looked great and the new rounded Reddit UI is very wasteful of screen real-estate in my opinion. Oh well...

**Comment by zenstorage** [comment]
I made a version for the sh interface; it doesn't have all the options yet, but I included the ones I considered most essential: https://github.com/zenstorage/Minimal-Reddit/raw/main/minimal_reddit_3rd.user.styl. Some options do not work because they are isolated with shadowRoot. You will need to install a userscript: https://greasyfork.org/scripts/459799-style-shadowdom.

Currently, the options that only work with the userscript are:

Searchbar:
  - Border radius
  - Remove trending
  - Remove nsfw"
  
  
You can suggest some that you consider important, I will try to prioritize them

@SEALCOOL13
