### ISSUE TITLE
Dropdown Navbar is not styled when viewing messages

### ISSUE THREAD

**Issue by tsuliwaensis** [zenstorage/Minimal-Reddit#3]
The dropdown navbar and the main navbar are not customized when viewing messages in the Inbox.

**Comment by zenstorage** [comment]
Do you mean in the url ```https://www.reddit.com/message/messages```?

**Comment by tsuliwaensis** [comment]
Yes

**Comment by zenstorage** [comment]
Thanks for the feedback, fixed.
